# Generated by Django 3.2.13 on 2022-06-08 08:04

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=project.models.upload_to)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
