# Generated by Django 3.2.13 on 2022-06-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20220608_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textureimage',
            old_name='image_url',
            new_name='image',
        ),
    ]
