# Generated by Django 3.2.13 on 2022-06-19 12:29

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_textureimage_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('scene', models.FileField(upload_to=project.models.scene_upload_to)),
            ],
        ),
    ]
