# Generated by Django 3.2.13 on 2022-06-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='scene',
            field=models.TextField(),
        ),
    ]
